version:             0.1.0.0
github:              "githubuser/mullvad-vpn-cli"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"
name:                "mullvad-vpn-cli"
extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/mullvad-vpn-cli#readme>

dependencies:
- base >= 4.7 && < 5
- http-client
- http-conduit
- yaml
- bytestring
- aeson
- json
- text
- containers

library:
  source-dirs: src

executables:
  mullvad-vpn-cli-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mullvad-vpn-cli

tests:
  mullvad-vpn-cli-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mullvad-vpn-cli
    - HUnit
